// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPVTBxbLx_4zUlVk4ifk__VtlOFPSG-Uc',
    appId: '1:1015362527585:web:c3282002937876e27ca520',
    messagingSenderId: '1015362527585',
    projectId: 'crudapp-40e03',
    authDomain: 'crudapp-40e03.firebaseapp.com',
    storageBucket: 'crudapp-40e03.appspot.com',
    measurementId: 'G-B0ZRYB37YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUYGoZ0SiXxi_xzAswnlEwugklFAh5vgQ',
    appId: '1:1015362527585:android:690d0ac39ca510bb7ca520',
    messagingSenderId: '1015362527585',
    projectId: 'crudapp-40e03',
    storageBucket: 'crudapp-40e03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVFQVJOVa_Lk7G3IhiFnpJMAFdFX1U27c',
    appId: '1:1015362527585:ios:513d9aaad2927d447ca520',
    messagingSenderId: '1015362527585',
    projectId: 'crudapp-40e03',
    storageBucket: 'crudapp-40e03.appspot.com',
    iosBundleId: 'com.example.loginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVFQVJOVa_Lk7G3IhiFnpJMAFdFX1U27c',
    appId: '1:1015362527585:ios:864503ec8c5467597ca520',
    messagingSenderId: '1015362527585',
    projectId: 'crudapp-40e03',
    storageBucket: 'crudapp-40e03.appspot.com',
    iosBundleId: 'com.example.loginRegister.RunnerTests',
  );
}
