// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBS5BFwlnU4pK_8_SlE-07SXmYSONoEE8',
    appId: '1:60269194876:web:e4110463acaef38a8563f9',
    messagingSenderId: '60269194876',
    projectId: 'music-3ab6b',
    authDomain: 'music-3ab6b.firebaseapp.com',
    storageBucket: 'music-3ab6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiFPM9JPN4ZF0NKhyXVF1Lg8_hGMCEZv0',
    appId: '1:60269194876:android:d559afdfb1197c2c8563f9',
    messagingSenderId: '60269194876',
    projectId: 'music-3ab6b',
    storageBucket: 'music-3ab6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKXnn2AD5iSj8vCa13Nv0ryW_W_eIlN0',
    appId: '1:60269194876:ios:6a3da52a1be3d79a8563f9',
    messagingSenderId: '60269194876',
    projectId: 'music-3ab6b',
    storageBucket: 'music-3ab6b.appspot.com',
    iosBundleId: 'com.example.loginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBKXnn2AD5iSj8vCa13Nv0ryW_W_eIlN0',
    appId: '1:60269194876:ios:1617f99e28e16a658563f9',
    messagingSenderId: '60269194876',
    projectId: 'music-3ab6b',
    storageBucket: 'music-3ab6b.appspot.com',
    iosBundleId: 'com.example.loginRegister.RunnerTests',
  );
}
